name: build-push-image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: [amd64, docker]
    container:
      image: node:24-bookworm
    name: 'Build & push docker image'
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: forge.lucaslemaire.fr/zwo
          username: zwo
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: forge.lucaslemaire.fr/zwo/gotontfy:latest
          file: Dockerfile
